# -*- coding: utf-8 -*-
course_hashes = [
 {:course=>"视练",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"视练",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"乐理（上）         和声（下）",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"作曲改题",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"复调基础（上）",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"视唱练耳",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"中史",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"芭蕾",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"爵士",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[1]}]},
 {:course=>"民二（刘）",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"音导二（张）",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"现代一",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"作曲",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"音科二",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"管一、提制一(曲)",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"现代二声乐二",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"音乐剧一",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"音乐剧二",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[2]}]},
 {:course=>"音乐基础",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"乐理（上）         和声（下）",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"作曲（小型作品写作）",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"论文写作",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"管弦乐配器（上）音导三",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"复调",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"舞蹈（踢踏）",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"形体与舞蹈",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"音乐工程设计",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"论文写作（上）",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"中史",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"中国音乐史",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"音乐美学与音乐作品研究",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"音乐教学法",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"民间音乐",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>1, :number=>[3]}]},
 {:course=>"艺管三",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"弦二、现打键盘二",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"管二、提制二",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"音技一             ",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"低提一现打一（夏）",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"民族班一（丁）",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"民乐一(顾)",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"弦一、现打键盘一",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"音导一",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"研",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"音乐学三",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"音乐剧三",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"音乐教育一",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"音科三",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"管弦四",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"民乐二钢琴二      作曲二指挥二    ",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"音乐学一",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"研",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"高起本四",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"高起本三",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"音学二、音工二（男）音教二（男）   音教二（女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>1, :number=>[4]}]},
 {:course=>"实用心理学",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>1, :number=>[5]}]},
 {:course=>"选",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>1, :number=>[6]}]},
 {:course=>"音乐基础",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"音乐设计基础",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"中史",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"民族管弦乐法                    ",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"高等数学基础",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"音乐心理学（下）",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"应用作曲与绘谱",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"舞台艺术",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"形体与舞蹈",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"中国传统音乐形态构建论析",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"论文写作（上）",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"曲式",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"戏曲（上）曲艺（下）",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"教育心理学",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"合唱指挥",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"文化产业与管理",
  :locations=>["北604"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"音乐汉语",
  :locations=>["北606"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"剧目",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>1, :number=>[7]}]},
 {:course=>"艺管二",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"声一",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"声二",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音剧二（陈）",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音学一",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音教二甲",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音教一甲",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音教二乙",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"数字媒体二",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音工二 ",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"研究生课程班 ",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音科一",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音乐治疗一",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音科三",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音乐剧三",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音乐教育一",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"研       黄允箴教授",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音工四",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"声乐三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"作曲四指挥四民作四声乐四",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"高起本四",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"高起本三",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"研",
  :locations=>["北604"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"留学生",
  :locations=>["北606"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"音乐剧四",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"钢琴二、作指二（女）          钢琴二、作指二、艺管三（男）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>1, :number=>[8]}]},
 {:course=>"德语",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"钢琴艺术史",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"作曲基础",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"语音正音",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"视练",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"视练",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"艺术设计史（下）",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"视练",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"视练",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"艺术管理3（上）艺管三",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"音乐设计基础",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"和声（上）         复调（下）",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"钢琴表演艺术理论与教学研究 ",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"音乐工程设计",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"和声（上）民族班",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"应用作曲与绘谱",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"3D影像基础",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"形体与舞蹈",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"民族民间音乐（上）世界音乐（下）音教三",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"论文写作（上）",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"曲式",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"合唱",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"戏剧中的音乐",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"曲式",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"合唱指挥理论与实践",
  :locations=>["北604"],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>1, :number=>[9]}]},
 {:course=>"博二外",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"钢琴二",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"高起本四",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"声乐一",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"音剧一",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"音学二上      音导一下",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"数字媒体二",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"钢琴一",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"音教一乙",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"数字媒体一",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"音教二",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"研",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"音科四",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"音科二",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"数字媒体三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"音乐教育一",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"作曲五指挥五",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"钢琴三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"声乐二、三、四",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"研",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"高起本三",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"研",
  :locations=>["北604"],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"民乐二（女）  民乐二(男)",
  :locations=>[nil],
  :time_expression=>[{:weekday=>1, :number=>[10]}]},
 {:course=>"指挥系室内乐",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"语音正音（上）",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"西方音乐精品中的文学名著",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"合唱社",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"视练",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"中外美术简史（上）",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"政治A  ",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"MIDI原理与编曲",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"计算机绘画",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"舞蹈社",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"现当代视觉艺术赏析",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"民族管弦乐法",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>1, :number=>[11]}]},
 {:course=>"音教一",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"选",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"团委",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"低提二、现代二（安）",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"数字媒体二",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"硕一",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"音导一",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"数字媒体一",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"到1月",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"选修",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"民作二民作一民指一",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>1, :number=>[12]}]},
 {:course=>"听力",
  :locations=>["中102语"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"实用音乐技能            ",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"外史",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"曲式",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"见习与实习",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"视练",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"乐理（上）         和声（下）",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"语文",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"思法（上）近现         代史（下）",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"语文",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>2, :number=>[1]}]},
 {:course=>"留学生",
  :locations=>["中102语"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"音乐治疗三",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"作曲三指挥三声乐三",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"音乐学二",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"音乐治疗一",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"作曲二上       管弦民甲一下(周)",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"音教一",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"民乐一           作曲一指挥一",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"音工一",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"杨                 艺管二",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>2, :number=>[2]}]},
 {:course=>"听力",
  :locations=>["中102语"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"钢琴音乐分析",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"东方音乐（上）世界音乐（下）音乐学四",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"和声   研究生课程班 王建民",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"文献选读、分析及实验设计",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"指挥",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"爵士音乐史",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"外史",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"作曲改题",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"西方音乐史",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"多媒体设计基础",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"曲式与作品分析",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"英语A",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"三、四十年代中国流行音乐研究",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"芭蕾",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"音乐教学法",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"乐理（上）         和声（下）",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"配器  音乐学三",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"语文",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"思法（上）近现         代史（下）",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"中史",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"英语",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"中史（上）外史（下）",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"英语",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>2, :number=>[3]}]},
 {:course=>"留学生",
  :locations=>["中102语"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"钢琴四",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"音乐治疗三",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"音教三",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"现打一",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"民乐三    现打三",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"音乐设计一",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"艺管三",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"数字媒体一",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"作曲三指挥三民作三音导三",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"硕一",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"作曲一",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"研",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"管乐三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"音乐剧一",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"音乐治疗二",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"管乐一",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"音教一",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"钢琴一民乐一",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"管弦二",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"屈燕华",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"音教二    音剧二（中）音剧三（外）",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"胡青",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"声乐二（女）          现代二、音剧二、声乐二、音导二（男）           音剧二、现代二（女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>2, :number=>[4]}]},
 {:course=>"总谱读法作曲二 （12点到13点）",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>2, :number=>[5]}]},
 {:course=>"经典感情作品演奏分析运用",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[5]}]},
 {:course=>"音乐名作与文学名作",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[5]}]},
 {:course=>"形体训练",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[5]}]},
 {:course=>"华尔兹",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>2, :number=>[5]}]},
 {:course=>"实用心理学",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[5]}]},
 {:course=>"选",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[6]}]},
 {:course=>"选",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[6]}]},
 {:course=>"选",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[6]}]},
 {:course=>"选",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>2, :number=>[6]}]},
 {:course=>"选",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[6]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"艺术管理4（下）艺管三",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"西方现代音乐创作中的理论与实践",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"指挥",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"音乐学概论（上）音乐学导论（下）音乐学一",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"外史",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"古琴音乐概论",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"西方音乐史",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"展演策划及实务（上）广告创意（下）艺管三 艺管二",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"外史",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"民族音乐学（上）民族音乐学音乐描写分析（下）音乐学四",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"作曲（影视音乐设计与混合乐队写作）音导三",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"音乐数字媒体技术",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"歌剧表演（美声）",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"中国歌剧（民声）声乐四、五",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"乐理（上）         和声（下）",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"配器 作曲",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"乐理（上）         和声（下）",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"思法（上）近现         代史（下）",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"语文",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北604"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北606"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"剧目表演",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>2, :number=>[7]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"研",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"音技二(安)",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"音教三",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"管弦三",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"音乐学三",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"音乐学二",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"钢琴三",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"音科三",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"现代三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"声乐四、五",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"弦乐一钢琴一",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"声乐一民乐一",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"音剧一音教一",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"杨                   音工一",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"徐鸣",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"屈燕华",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"汤亚汀",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"张学君",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"胡青",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"宋晓琳",
  :locations=>["北604"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"余未来",
  :locations=>["北606"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"音乐剧三",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>2, :number=>[8]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"音乐欣赏",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"合唱与指挥",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"视练",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"艺管实务",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"曲式",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"爵士音乐理论与创编（下）",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"戏曲（上）曲艺（下）",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"数字媒体艺术（数字媒体规划方向）数字媒体三 ",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"戏曲打击乐基础",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"作曲作品",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"外史",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"政治B",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"大型曲式（上）音乐学分析方法与综合实践（下）音乐学四",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"西方音乐史（下）",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"歌剧表演（美声）",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"和声（上）         ",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"配器 作曲",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"和声（上）         复调（下）",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"古汉语",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北604"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北606"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"剧目表演",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>2, :number=>[9]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"音乐治疗二",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"音教二",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"新疆班二",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"艺管二艺管三",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"音教三",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"现器二",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"民乐三、",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"民乐二",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"作曲",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"音工三",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"硕一",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"高起本三",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"弦乐三音学三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"声乐四、五",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"音技二",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"声乐二民乐二",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"音乐学一",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"徐鸣",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"屈燕华",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"汤亚汀",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"张学君",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"胡青",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"宋晓琳",
  :locations=>["北604"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"余未来",
  :locations=>["北606"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"音乐剧三",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"管弦二（男、女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>2, :number=>[10]}]},
 {:course=>"项目管理（下）",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"合唱艺术实践",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"合唱",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"音乐声学",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"大学英语口语",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"现代音乐演唱演奏",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"艺术家的经营与管理选修",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"作曲作品",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"英语C",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"通俗音乐作品赏析与演唱",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"影像编辑(下)",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"专业计算机基础",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"木兰扇",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"形体与舞蹈",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"芭蕾音乐",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"和声改题",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"中外优秀电视片赏析",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"素描（上）",
  :locations=>["北219"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"剧目",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>2, :number=>[11]}]},
 {:course=>"数字媒体三",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"音乐剧一、二",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"提制三音导三音科三",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选修",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"作曲",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"硕一",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"数字媒体二",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"数字媒体一",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"作曲",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"选",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"数字媒体二",
  :locations=>["北219"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"音乐剧四",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>2, :number=>[12]}]},
 {:course=>"音乐文献编译二外",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"西方音乐史",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"音乐治疗理论",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"马基",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"舞蹈（踢踏）",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"管弦乐配器",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"思法（上）近现         代史（下）",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"毛邓三（上）",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"毛邓三（上）",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"毛邓三（上）",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"语文",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"色彩（上）构成（下）数字媒体二",
  :locations=>["北219"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"素描",
  :locations=>["北106"],
  :time_expression=>[{:weekday=>3, :number=>[1]}]},
 {:course=>"研",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"音乐学一",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"音乐治疗一",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"作曲二指挥二音教二",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"音乐剧三",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"作曲三指挥三",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"艺管二现代一",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"音教四音剧四作指四",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"民乐四现代四",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"声乐四",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"管弦一",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"数字媒体一",
  :locations=>["北106"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"表演",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>3, :number=>[2]}]},
 {:course=>"德语",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"键盘演奏",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"爵士音乐理论与创编",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"21世纪星新音乐新体验",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"音乐体裁与风格",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"视觉传达（上）",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"中国音乐史",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"欧洲中世纪音乐",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"见习与实习",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"西方音乐史(下)",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"马基",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"唐代音乐的理论研究与实践",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"管弦乐配器",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"戏曲、曲艺摹唱（上）戏曲、曲艺概论（下）音乐学二",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"音乐数字媒体艺术",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"教学法",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"爵士",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"和声（上）         复调（下）",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"管弦乐配器",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"和声改题补课",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"思法（上）近现         代史（下）",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"曲式",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"论文写作（上）",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"毛邓三（上）",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"毛邓三（上）",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"毛邓三（上）",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"语文",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"曲式与作品分析（下）作曲二指挥二民作二音导二",
  :locations=>["北606多"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"素描",
  :locations=>["北106"],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>3, :number=>[3]}]},
 {:course=>"声乐二",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音科二",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"现器三",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"选",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音教一",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"艺管三",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"艺管二",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"研",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音乐治疗三",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"数字媒体三",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"民乐二",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"研",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"作曲四指挥四",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音科一",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"民乐三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音乐教育二、三",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音乐剧二",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"弦乐二钢琴二",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"作曲三指挥三",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"作曲",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"作指一声乐一音学一",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"管乐三",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音剧四声乐五",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"钢琴四",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音工四艺管四",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"管弦四音学四",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"音剧一钢琴一",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"数字媒体一",
  :locations=>["北106"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"声乐三",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"管弦一（男、女）民乐一（男）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>3, :number=>[4]}]},
 {:course=>"键盘演奏",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>3, :number=>[5]}]},
 {:course=>"研进修班       秦诗乐",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>3, :number=>[5]}]},
 {:course=>"大学计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>3, :number=>[5]}]},
 {:course=>"舞蹈社",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[5]}]},
 {:course=>"华尔兹",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[5]}]},
 {:course=>"和声改题补课",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[5]}]},
 {:course=>"音科二",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>3, :number=>[6]}]},
 {:course=>"音导一",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>3, :number=>[6]}]},
 {:course=>"选",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[6]}]},
 {:course=>"作曲",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[6]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"歌剧分析与研究",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"口语",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"西方弦乐艺术史",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"数字动画设计",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"美术概论",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"传播学原理(上）媒体实务（下）艺管二",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"复调与赋格",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"中国音乐美学（上）音乐学三",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"戏曲常识",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"数字影像设计",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"英语正音",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"20世纪音乐分析",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"中国音乐史（上）",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"电子音乐概论（上）流行音乐概论（下）音导三音科三",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"计算机编程",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"教学法",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"退管委舞蹈社",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"和声（上）         复调（下）",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"戏曲音乐写作一        改题    研究生课程班",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"和声改题补课",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"思法（上）近现         代史（下）",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"曲式",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"论文写作（上）",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"音乐审美与民族心理学",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"论文写作（上）",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"赏析",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"语文",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"表演（小品）",
  :locations=>["排110"],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>3, :number=>[7]}]},
 {:course=>"留学生",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"指挥三",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"留学生",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"管弦三",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"数字媒体二",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"艺管三",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"指挥二民作二",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"民乐",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"数字媒体三",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"音乐剧二",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"研",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"数字媒体三",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"音科二",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"声乐三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"音乐教育二、三",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"管乐二",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"作曲",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"管弦一",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"民乐三",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"民乐四",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"研",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"钢琴四现打四",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"进修班",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"声乐一现代一",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"声乐三",
  :locations=>["排110"],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"音工一、音剧一（女）         钢琴一、音学一、音剧一（男）        音学一（女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>3, :number=>[8]}]},
 {:course=>"中国概况",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[9]}]},
 {:course=>"现代音乐演唱演奏 ",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>3, :number=>[9]}]},
 {:course=>"台词",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[9]}]},
 {:course=>"和声改题补课（形任会让）",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[9]}]},
 {:course=>"表演（小品）",
  :locations=>["排110"],
  :time_expression=>[{:weekday=>3, :number=>[9]}]},
 {:course=>"张慧梁副教授",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[10]}]},
 {:course=>"研",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>3, :number=>[10]}]},
 {:course=>"民族班 一",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[10]}]},
 {:course=>"作曲",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[10]}]},
 {:course=>"声乐三",
  :locations=>["排110"],
  :time_expression=>[{:weekday=>3, :number=>[10]}]},
 {:course=>"创意系统设计（上）虚拟现实设计（下）数字媒体二、三",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"音乐声学（一） 研 华天礽教授",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"中外美术作品欣赏",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"二十世纪和声专题研究系列选修",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"专业计算机基础",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"表演",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"表演",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"中外室内乐赏析选刘灏讲师",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"和声改题补课",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"经典英文影片阅读理解",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"近现代合唱作品排练",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"表演（小品）",
  :locations=>["排110"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"表演",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>3, :number=>[11]}]},
 {:course=>"选",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"选修",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"音科一",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"音乐剧一",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"音乐剧二（分班）",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"选",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"作曲",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"选",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"选",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"声乐三",
  :locations=>["排110"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"音乐剧二（分班）",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>3, :number=>[12]}]},
 {:course=>"听力",
  :locations=>["中102语"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"键盘演奏",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"视练",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"视练",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"视练",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"视练",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"视唱练耳",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"芭蕾",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"马基",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"艺概              张",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"艺概    杨",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"马基",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"构成（上）",
  :locations=>["北106"],
  :time_expression=>[{:weekday=>4, :number=>[1]}]},
 {:course=>"留学生",
  :locations=>["中102语"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"音科一",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"民二（刘）",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"音导二（张）",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"民族班一（丁）",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"民乐一(顾)",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"管一、提制一(曲)",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"音乐剧二",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"管弦二",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"民乐三现代三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"管弦三",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"现打二钢琴二",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"总谱读法",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"数字媒体三",
  :locations=>["北106"],
  :time_expression=>[{:weekday=>4, :number=>[2]}]},
 {:course=>"法语",
  :locations=>["中102语"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"俄语（上）",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"公共事务（上）",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"民歌摹唱（上）民器摹唱（下）音乐学一",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"数字音频制作",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"见习与实习",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"作品分析                         ",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"文献研读与研习",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"中国音乐史  音乐学三",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"芭蕾",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"马基",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"曲式",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"和声A（上）",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"曲式",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"钢琴公开课",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"艺概",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"马基",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"作曲基础",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"9点到1点",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"作曲进修班",
  :locations=>["北606"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"构成（上）",
  :locations=>["北106"],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>4, :number=>[3]}]},
 {:course=>"声乐三",
  :locations=>["中102语"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"声乐四",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"艺管三",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"弦二、现打键盘二",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"管二、提制二",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"低提一现打一（夏）",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"音技一(丁)",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"钢琴一",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"弦一、现打键盘一",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"民族班二",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"音导三",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"音乐治疗二",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"研究生",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"音乐学四",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"音乐剧一",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"艺管二声乐二音乐学二",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"弦乐三",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"民作二指挥二",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"现打三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"音教",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"作指三   钢琴三",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"音剧二音工二",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"民乐三",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"总谱读法",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"作曲进修班",
  :locations=>["北606"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"数字媒体三",
  :locations=>["北106"],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"声乐一、作指一（男）         作指一、声乐一（女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>4, :number=>[4]}]},
 {:course=>"视唱练耳",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[5]}]},
 {:course=>"动漫社",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>4, :number=>[5]}]},
 {:course=>"MIDI",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>4, :number=>[5]}]},
 {:course=>"形体训练",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[5]}]},
 {:course=>"9点到1点",
  :locations=>["北603"],
  :time_expression=>[{:weekday=>4, :number=>[5]}]},
 {:course=>"张晖",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[6]}]},
 {:course=>"团委",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>4, :number=>[6]}]},
 {:course=>"音导一",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>4, :number=>[6]}]},
 {:course=>"声乐二",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[6]}]},
 {:course=>"键盘演奏",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"口语",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"艺术管理1（上）艺术管理2（下）艺管二",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"教育心理学",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"视练",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"音乐技术理论（下）",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>" 当代音乐 ",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"多媒体艺术实践",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"中国宗教音乐与民俗（上）中国传统音乐与社会（下）音乐学四",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"影像编辑（下）",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"数字音频制作",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"戏曲演唱（民声）",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"剧目表演",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"配器基础下",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"和声",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"艺术概论",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"艺概",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"剧目",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>4, :number=>[7]}]},
 {:course=>"音科一数字媒体一",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"留学生",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"声一",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"声二",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音剧二（陈）",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音学一",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音教二甲",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音教一",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音教二乙",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音乐剧一",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"作曲四、指挥四",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"数字媒体二",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"数字媒体二",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音导一",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"声乐四",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音乐剧三",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音科二",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"作曲一指挥一音计一",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音乐学三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音工三",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"音乐剧四",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"艺管三（女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>4, :number=>[8]}]},
 {:course=>"键盘演奏",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"口语",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"视练",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"视练",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"法学基础",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"中国传统音乐分析上少数民族音乐下音乐学三、四刘红\\萧梅教授",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"音工专业课",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"音乐技术理论",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"英语 硕二",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"音乐音响分析",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"作曲（室内乐与电子音乐写作）音导二",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"交互式设计（下）",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"数字音乐创编（上）音响设计（下）数字媒体三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"剧目表演",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"和声",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"和声B（上）",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"艺概",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"剧目",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>4, :number=>[9]}]},
 {:course=>"音科一",
  :locations=>["中105电钢"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"留学生",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"音剧一",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"音学二上      音导一下",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"艺管二",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"安栋",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"音乐剧二",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"硕二",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"音科三",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"数字媒体二",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"音乐剧三",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"民族班民作一",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"作曲二",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"艺管三声乐三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"音乐剧四",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"音教一（女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>4, :number=>[10]}]},
 {:course=>"合唱艺术实践",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>4, :number=>[11]}]},
 {:course=>"音乐艺术策划与经营管理",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[11]}]},
 {:course=>"合唱指挥概论",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>4, :number=>[11]}]},
 {:course=>"视练",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>4, :number=>[11]}]},
 {:course=>"数字音频制作",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>4, :number=>[11]}]},
 {:course=>"台词",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[11]}]},
 {:course=>"台词",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>4, :number=>[11]}]},
 {:course=>"中外优秀影片赏析",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>4, :number=>[11]}]},
 {:course=>"选",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>4, :number=>[12]}]},
 {:course=>"选",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>4, :number=>[12]}]},
 {:course=>"选",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>4, :number=>[12]}]},
 {:course=>"低提二、现代二（安）",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>4, :number=>[12]}]},
 {:course=>"音导二",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>4, :number=>[12]}]},
 {:course=>"音乐剧一",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>4, :number=>[12]}]},
 {:course=>"音乐剧二",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>4, :number=>[12]}]},
 {:course=>"选",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>4, :number=>[12]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"作曲技术综合理论",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"音乐声学",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"摄影基础(下)",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"视练",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"视练",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"形体训练",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"芭蕾",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"和声（上）         复调（下）",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"毛邓三           张",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"毛邓三           杜",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>5, :number=>[1]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"音乐治疗二",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"华天礽教授",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"数字媒体一",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"音教一甲(曲)",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"作曲二上       管弦民甲一下(周)",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"声乐一",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"音乐剧一",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"现打二",
  :locations=>["北215多"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"音教三音剧三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"音工三艺管三",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>5, :number=>[2]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"精读",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"中国音乐美学 研 郭树荟副教授",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"西方管乐艺术史",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"德国音乐教育",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"摄影基础(下)",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"口语",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"影像基础",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"民歌（上）民器（下）",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"视练",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"西方音乐史（上）",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"技术理论分析与教学",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"音乐教学法",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"芭蕾",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"儒道佛",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"毛邓三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"毛邓三",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"英语",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"英语",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"复调与赋格",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>5, :number=>[3]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"留学生",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"管弦二",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"研",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"数字媒体一",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"音教一乙",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"留学生",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"数字媒体二",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"管弦三声乐三",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"作曲一",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"音乐学三",
  :locations=>["中607多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"音教三",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"音剧三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"音乐治疗二",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"音乐剧二",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"研",
  :locations=>["北214多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"作指三钢琴三",
  :locations=>["北414多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"民乐三现代三",
  :locations=>["北415多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"屈燕华",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"胡青",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"音乐技术二",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"钢琴一、现代一（女）          民乐一（女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>5, :number=>[4]}]},
 {:course=>"指挥",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>5, :number=>[5]}]},
 {:course=>"中国民族民间音乐解析",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>5, :number=>[5]}]},
 {:course=>"歌剧经典剧目分析",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>5, :number=>[5]}]},
 {:course=>"20世纪西方音乐名作赏析 选",
  :locations=>["北216多"],
  :time_expression=>[{:weekday=>5, :number=>[5]}]},
 {:course=>"钢琴教学法",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>5, :number=>[5]}]},
 {:course=>"小乐队编配方法",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>5, :number=>[5]}]},
 {:course=>"弦乐名作赏析",
  :locations=>["北606多"],
  :time_expression=>[{:weekday=>5, :number=>[5]}]},
 {:course=>"10年上学期",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>5, :number=>[6]}]},
 {:course=>"选",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>5, :number=>[6]}]},
 {:course=>"选",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>5, :number=>[6]}]},
 {:course=>"选",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>5, :number=>[6]}]},
 {:course=>"选",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>5, :number=>[6]}]},
 {:course=>"选",
  :locations=>["北606多"],
  :time_expression=>[{:weekday=>5, :number=>[6]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"音乐作品分析",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"室内乐",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"政治",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"艺术评论（上）",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"打击乐合奏",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"毛邓三         喻",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"意大利语",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"口语",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"民歌（上）民器（下）",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>" ",
  :locations=>["中603多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"英语A",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"音乐数字媒体艺术",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"歌剧表演（美声）",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"中国歌剧（民声）声乐四、五",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"英语",
  :locations=>["北606多"],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>5, :number=>[7]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"数字媒体三",
  :locations=>["中213多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"声乐四、五",
  :locations=>["中215多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"博士",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"艺管三",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"指挥一",
  :locations=>["中413多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"声乐三音学三",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"声乐一",
  :locations=>["中417多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"留学生",
  :locations=>["中419多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"作指三钢琴三",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"硕一",
  :locations=>["中605多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"音科二",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"音教三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"声乐四、五",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"徐鸣",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"屈燕华",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"汤亚汀",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"张学君",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"胡青",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"宋晓琳",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"余未来",
  :locations=>["北606多"],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"音学二（女）          艺管二、音工一、音教一、现代一（男）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>5, :number=>[8]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"艺概            王",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"复调与赋格",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"艺术评论（上）",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"毛邓三         喻",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"和声",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"民歌（上）民器（下）",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"影像编辑（上）",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"计算机",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"歌剧表演（美声）",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"英语",
  :locations=>["北606多"],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"体育",
  :locations=>[nil],
  :time_expression=>[{:weekday=>5, :number=>[9]}]},
 {:course=>"听力",
  :locations=>["中103语"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"音教三音剧三",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"作曲二指挥二民作二",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"艺管三",
  :locations=>["中219多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"管弦三",
  :locations=>["中415多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"音乐学一",
  :locations=>["中601多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"民乐二现代三",
  :locations=>["中602多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"数字媒体三",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"作指三钢琴三",
  :locations=>["北102机"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"声乐四、五",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"徐鸣",
  :locations=>["北416多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"屈燕华",
  :locations=>["北418多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"汤亚汀",
  :locations=>["北601多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"张学君",
  :locations=>["北602多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"胡青",
  :locations=>["北603多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"宋晓琳",
  :locations=>["北604多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"余未来",
  :locations=>["北606多"],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"音工二（女）艺管二（女）",
  :locations=>[nil],
  :time_expression=>[{:weekday=>5, :number=>[10]}]},
 {:course=>"数字媒体艺术",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>5, :number=>[11]}]},
 {:course=>"英语B ",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>5, :number=>[11]}]},
 {:course=>"3D影像基础",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>5, :number=>[11]}]},
 {:course=>"表演",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[11]}]},
 {:course=>"表演",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>5, :number=>[11]}]},
 {:course=>"表演",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>5, :number=>[11]}]},
 {:course=>"数字媒体三",
  :locations=>["中214多"],
  :time_expression=>[{:weekday=>5, :number=>[12]}]},
 {:course=>"硕一",
  :locations=>["中217多"],
  :time_expression=>[{:weekday=>5, :number=>[12]}]},
 {:course=>"数字媒体二",
  :locations=>["北101机"],
  :time_expression=>[{:weekday=>5, :number=>[12]}]},
 {:course=>"音乐剧一",
  :locations=>["北103形"],
  :time_expression=>[{:weekday=>5, :number=>[12]}]},
 {:course=>"音乐剧二（分班）",
  :locations=>["北104形"],
  :time_expression=>[{:weekday=>5, :number=>[12]}]},
 {:course=>"音乐剧二（分班）",
  :locations=>["中107"],
  :time_expression=>[{:weekday=>5, :number=>[12]}]}]

ActiveRecord::Base.transaction do
  User.where('name = "yedx" or name = "xiao"').destroy_all
  Student.where('sid like "sid-y%"').destroy_all
  Teacher.where('tid like "tid-x%"').destroy_all
  courses = Course.where('cid like "cid-x%"')
  courses.each do |course|
    user_id = course.course_teachers[0].teacher_user_id
    course.course_teachers.destroy_all
    CourseStudentAssign.where('teacher_user_id = ?', user_id).destroy_all
  end
  courses.destroy_all

  teacherx = Teacher.create do |teacher|
    user = User.create(:name => 'xiao',
                       :password => '1234',
                       :email => 'xiao@edu.dev')

    user.set_role :teacher

    teacher.real_name = '肖少富'
    teacher.tid = 'tid-x'
    teacher.user = user
  end

  studenty = Student.create do |student|
    user = User.create(:name => 'yedx',
                       :password => '1234',
                       :email => 'ye@edu.dev')

    user.set_role :student

    student.real_name = '叶大雄'
    student.sid = 'sid-y'
    student.user = user
  end

  course_hashes.reduce([1, [], []]) do |array, hash|
    name = hash[:course]
    id = array[0]
    course_names = array[1]
    time_expressions = array[2]
    semester = Semester.now
    location = hash[:locations][0]
    time_expression = hash[:time_expression]

    next [id, course_names.uniq, time_expressions.uniq] if course_names.include?(hash[:course]) ||
      time_expressions.include?(hash[:time_expression])
    
    course = Course.create(:name => name,
                           :cid => "cid-x#{id}")

    course.add_teacher(:semester => semester,
                       :teacher_user => teacherx.user)
                       
    course.set_course_time(:semester => semester,
                           :teacher_user => teacherx.user,
                           :time => time_expression)

    studenty.user.add_course(:semester => semester,
                             :teacher_user => teacherx.user,
                             :course => course)

    course_names << name
    time_expressions << time_expression

    [id + 1, course_names.uniq, time_expressions.uniq]
  end

end
