#!/bin/sh

### BEGIN INIT INFO
# Provides:       nginx 
# Required-Start: 
# Required-Stop:
# Default-Start:  2 3 5
# Default-Stop:
# Description:    Start the nginx server
### END INIT INFO

NGINX_BIN=/usr/local/nginx/sbin/nginx
NGINX_PID_FILE=/usr/local/nginx/logs/nginx.pid

case "$1" in

  start)
    $NGINX_BIN
    echo "nginx started"
    ;;

  stop)
    kill -INT `cat $NGINX_PID_FILE`
    echo "nginx stoped"
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: nginx {start|stop|restart}"
    ;;

esac

exit 0

