source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'mysql2'
gem 'json'

gem 'therubyracer'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'system_timer'

gem 'haml'
gem 'redis'

gem 'memcache-client', '~> 1.8.5', :require => 'memcache'
gem 'ap'

gem 'will_paginate', '~> 3.0.2'
gem 'nokogiri'
gem 'oauth'
gem 'uuidtools', :require => 'uuidtools'
gem 'responds_to_parent'
gem 'rubyzip', '0.9.4', :require => 'zip/zip'
gem 'resque'

# paperclip
gem 'paperclip', '~> 2.4'
gem 'paperclip-meta'

gem 'weibo'

gem 'coderay'
gem 'haml-coderay'

gem 'grit'
gem 'rmagick', :require => 'RMagick'

gem 'unicorn'
# 自己写的
gem 'pie-ui'
