source 'http://ruby.taobao.org'

gem 'rails', '3.1.3'
gem 'mysql2'
gem 'json'
gem 'therubyracer'
gem 'awesome_nested_set'

gem 'thinking-sphinx', '2.0.10'
gem 'rmmseg-cpp'
gem 'redis-namespace'
gem 'redis-search', :path => 'vendor/redis-search'
gem 'streamio-ffmpeg'
gem 'rcov', :platform => :mri_18
gem 'simplecov', :platform => :mri_19
gem 'spork', '~> 0.9.2'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'juggernaut', '2.1.1'
gem 'system_timer'
gem 'haml'
gem 'redis'
gem 'memcache-client', '~> 1.8.5', :require => 'memcache'
gem 'will_paginate', '~> 3.0.2'
gem 'nokogiri'
gem 'uuidtools', :require => 'uuidtools'
gem 'responds_to_parent'
gem 'rubyzip', '0.9.4', :require => 'zip/zip'
gem 'resque'

# paperclip
gem 'paperclip', '~> 2.7'
gem 'paperclip-meta'

gem 'coderay'
gem 'haml-coderay'

gem 'grit'
gem 'rmagick', :require => 'RMagick'

gem 'unicorn'

group :test, :development do
  gem 'rspec-rails'
end

group :test do
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'factory_girl', '~> 2.6'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'timecop'
end
